# Generated by Django 4.2.13 on 2024-07-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('captcha', models.CharField(max_length=10)),
                ('creat_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
