# Generated by Django 4.2.13 on 2024-07-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='text',
            field=models.TextField(),
        ),
    ]
