# Generated by Django 4.2.13 on 2024-07-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_text_blog_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='blog_ky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog'),
        ),
    ]
